#!/usr/bin/env bash

# setup autodoc
echo ; echo '--> Setting up autodoc...'
sphinx-apidoc -f -o doc/source prost

# setup version
echo ; echo '--> Setting up version...'
echo '# Autogenerated by build.sh.' > prost/_version.py
echo __version__ = \"`cat VERSION`\" >> prost/_version.py

# Build docs
echo ; echo '--> Building docs...'
(cd doc; make html)

# Build it
echo ; echo '--> Building package...'
python setup.py build
